name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-04-09"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"			#d1数据库绑定名默认不可修改
database_name = "email"		#d1数据库名字
database_id = "b1b1a63a-6ef5-4e6d-8e8c-b6d9e8feb810"		#d1数据库id

[[kv_namespaces]]
binding = "kv"			#kv绑定名默认不可修改
id = "0fa01d4b299e481b9de060ece9e7785c"					#kv数据库id

#(可选)
[[r2_buckets]]
binding = "r2"			#r2对象存储绑定名默认不可修改
bucket_name = "email"		#r2对象存储桶的名字

[assets]
binding = "assets"		#静态资源绑定名默认不可修改
directory = "./dist"	#前端vue项目打包的静态资源存放位置,默认dist
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]	#定时任务每天晚上12点执行


#[vars]
#orm_log = false
#domain = []				#邮件域名可可配置多个 示例: ["example1.com","example2.com"]
#admin = ""				#管理员的邮箱	示例: admin@example.com
#jwt_secret = ""			#jwt令牌的密钥,随便填一串字符串
